# Generated by Django 2.1 on 2018-08-31 07:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('abstract', models.TextField(default=' ', max_length=500)),
                ('BibTex', models.TextField(default=' ', max_length=200)),
                ('PaperPDF', models.FileField(default=' ', upload_to='')),
                ('PeerPDF', models.FileField(default=' ', upload_to='')),
                ('author', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
