# Generated by Django 2.1 on 2018-08-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paperID', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('abstract', models.TextField(default=' ', max_length=500)),
                ('BibTex', models.TextField(default=' ', max_length=200)),
                ('PaperPDF', models.FileField(default=' ', upload_to='')),
                ('PeerPDF', models.FileField(default=' ', upload_to='')),
            ],
        ),
    ]
