# Generated by Django 2.1 on 2018-09-04 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('PublicationType', models.TextField(default=' ', max_length=50, verbose_name='Type of Publication')),
                ('Publisher', models.TextField(default=' ', max_length=50)),
                ('NumOfPages', models.TextField(default=' ', max_length=10, verbose_name='Number of Pages')),
                ('Date', models.DateTimeField(verbose_name='date published')),
                ('Abstract', models.TextField(default=' ', max_length=500)),
                ('BibTex', models.TextField(default=' ', max_length=200)),
                ('PaperPDF', models.FileField(default=' ', upload_to='media/', verbose_name='Research Paper')),
                ('PeerPDF', models.FileField(default=' ', upload_to='media/', verbose_name='Peer Review')),
                ('Author', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
