# Generated by Django 2.1 on 2018-09-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='Title',
            field=models.CharField(max_length=100),
        ),
    ]
