# Generated by Django 2.1 on 2018-08-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_auto_20180831_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='PaperPDF',
            field=models.FileField(default=' ', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='PeerPDF',
            field=models.FileField(default=' ', upload_to='media/'),
        ),
    ]
