# Generated by Django 2.1 on 2018-09-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_auto_20180905_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='Abstract',
            field=models.TextField(default=' ', max_length=2000),
        ),
        migrations.AlterField(
            model_name='paper',
            name='BibTex',
            field=models.TextField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='paper',
            name='NumOfPages',
            field=models.TextField(default=' ', max_length=50, verbose_name='Number of Pages'),
        ),
    ]
