# Generated by Django 2.1 on 2018-09-04 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_node_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='Organisation',
        ),
    ]
